version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "tacocloud"
      POSTGRES_USER: "tacouser"
      POSTGRES_PASSWORD: "tacopassword"
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080