taco:
  orders:
    pageSize: 20

spring:
  thymeleaf:
    cache: false
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName: org.h2.Driver
    username: sa
    password:
    scripts:
      - classpath:jdbc/schema.sql
      - classpath:jdbc/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

server:
  port: 8443
  ssl:
    key-alias: tomcat
    key-store: mykeys.jks
    key-store-password: 112233
    key-password: 112233

logging:
  path: /var/logs/
  file: tacoCloud.log
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
